apiVersion: v1
kind: Service
metadata:
  name: logging-fluentbit-sidecar
  labels:
    app: logging-fluentbit-sidecar
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: website
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-fluentbit-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    spec:
      containers:
        - name: aspnet-web
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          volumeMounts:
            - mountPath: 
              name:


