apiVersion: v1
data:
  fluent-bit.conf: |
    [Service]
        Daemon    false
        Flush    5
        Http_Listen    0.0.0.0
        Http_Port    2022
        Http_Server    On
        Log_Level    info
        Parsers_File    /fluent-bit/config/parsers.conf
        Plugins_File    /fluent-bit/config/plugins.conf
        Storage.path    /var/log/flb-storage/
        Storage.sync              normal
        Storage.checksum          off
        Storage.max_chunks_up     128
        Storage.backlog.mem_limit 12M
        Buffer_Workers    6
    @INCLUDE stdout-kubernetes.conf
    [Input]
        Name    tail
        Path

    /var/log/applogs/*/*error*.log,
    /var/log/applogs/*/*/*error*.log,
    /var/log/accesslogs/*/*error*.log,
    /var/log/accesslogs/*/*/*error*.log,
    /var/log/applogs/satellite-*/*error*.log.*,
    /var/log/accesslogs/satellite-*/*error*.log.*

        Path_Key    file
        Exclude_Path
    *trace*T*.log,
    *.gz,
    *.zip,
    */gc.log,
    */gc-*.log
        Refresh_Interval    20
        Rotate_Wait    10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size 64k
        Ignore_Older    30m
        Skip_Long_Lines    true
        Read_from_Head false
        DB    /var/log/flb_ke_tail.db
        Mem_Buf_Limit    100MB
        Multiline.Parser   java
        Tag    kelog.*
    [Input]
        Name    tail
        Path

    /var/log/applogs/*/*.log,
    /var/log/applogs/*/*/*.log,
    /var/log/accesslogs/*/*.log,
    /var/log/accesslogs/*/*/*.log,
    /var/log/applogs/satellite-*/*.log.*,
    /var/log/accesslogs/satellite-*/*.log.*

        Path_Key    file
        Exclude_Path
    
    *trace*T*.log,
    *.gz,
    *.zip,
    */gc.log,
    */gc-*.log,
    *error*

        Storage.type   filesystem
        Refresh_Interval    20
        Rotate_Wait    10
        Ignore_Older    30m
        Buffer_Chunk_Size 64k
        Buffer_Max_Size 132k
        Skip_Long_Lines    true
        Read_from_Head false
        DB    /var/log/flb_ke_tail.db
        Mem_Buf_Limit    1500MB
        Parser    any
        Tag    kelog.*

    [Filter]
        Name    parser
        Match    kelog.*
        Key_Name    file
        Parser    k8s
        Preserve_Key    true
        Reserve_Data    true
    [Filter]
        Name lua
        Match kelog.*
        call update_tag
        script /opt/loki-logs-filter/main.lua
        protected_mode true
    [Filter]
        Name          rewrite_tag
        Match         kelog.*
        Rule          $lokitag .*  to.loki.$lokitag false
        Emitter_Name  re_emitted
        Emitter_Storage.type filesystem
        Emitter_Mem_Buf_Limit 5G
    [FILTER]
        Name record_modifier
        Match to.loki.*
        Remove_key lokitag
    [Output]
        Name    fast
        Match    kelog.*
        Default_Topics    k8s-cloud-log-online
        Default_Cluster    dig-all
        Backend    file:///opt/fast/rules.json
        Tag_Prefix    kelog.var.log.applogs., kelog.var.log.accesslogs.
        Regex_Parser    (?P<service_id>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\_(?P<service_group>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\_(?P<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\_(?P<pod_namespace>[a-z0-9](?:[-a-z0-9]*[a-z0-9])+)\_(?P<container_name>[a-z0-9](?:[-z-z0-9]*[a-z0-9])+)\.(?P<file>.*)
        Cluster_Config_File    /opt/fast/config.json
        Workers    6
        Storage.total_limit_size 5G
    [Output]
        Name    forward
        Alias   grafana-loki
        Match   to.loki.*
        Host    127.0.0.1
        Port    5140
        Workers 12
        Net.connect_timeout   20
        Storage.total_limit_size 5G
  parsers.conf: |
    [PARSER]
        Name    docker
        Format    json
        Time_Key    time
        Time_Format    %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    true
    [PARSER]
        Name    java-multiline
        Format    regex
        Regex    /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
        Time_Key    time
        Time_Format    %Y-%m-%d %H:%M:%S
    [PARSER]
        Name    nginx
        Format    regex
        Regex    ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^"]*)" "(?<agent>[^"]*)")
        Time_Key    time
        Time_Format    %Y-%m-%d %H:%M:%S
    [PARSER]
        Name    k8s
        Format    regex
        Regex    (?<service_id>[^\/_]+)_(?<service_group>[^\/_]+)_(?<pod_name>[^\/_]+)_(?<pod_namespace>[^\/_]+)_(?<container_name>[^\/_]+)
    [PARSER]
        Name    any
        Format    regex
        Regex    .+
        Time_Key    time
        Time_Format    %Y-%m-%d %H:%M:%S
  plugins.conf: |-
    [PLUGINS]
        Path /fluent-bit/bin/out_fast.so
  stdout-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Exclude_Path
    *bird-exporter*,
    *calico*,
    *cfs*,
    *clean-logs*,
    *infra-loki*,
    *kms-agent*,
    *node-exporter*,
    *dns*,
    *fluent*,
    *dajing*,
    *default-http*,
    *kruise*,
    *s3-rm*,
    *chaosblade*,
    *csi-cbs*,
    *ip-masq*,
    *kube-proxy*,
    *node-problem-detector*,
    *qos-agent*,
    *serf-agent*,
    *tke*
        Refresh_Interval  20
        Rotate_Wait       10
        Ignore_Older      30m
        Skip_Long_Lines   true
        Read_from_Head    false
        DB                /var/log/flb_ke_tail.db
        Mem_Buf_Limit     100MB
        Parser            docker
        Tag               kube.*
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Use_Kubelet         true
        Kubelet_Port        10250
        Kubelet_Host        ${KUBELET_HOST}
        Merge_Log           Off
        Buffer_Size         10MB
        Labels              On
        Annotations         Off
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude Off
        tls.verify          Off
    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes
    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        labels
    [FILTER]
        Name record_modifier
        Match kube.*
        Record file terminal
        Allowlist_key log
        Allowlist_key pod_name
        Allowlist_key namespace_name
        Allowlist_key container_name
        Allowlist_key service_group
        Allowlist_key service_id
    [FILTER]
        Name modify
        Match kube.*
        Rename namespace_name pod_namespace
    [Output]
        Name    forward
        Alias   grafana-kube-loki
        Match   kube.*
        Host    127.0.0.1
        Port    5140
        Workers 6
        Net.connect_timeout   20
        Storage.total_limit_size 5G
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |

  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:plugins.conf: {}
      manager: kubectl-edit
      operation: Update
      time: "2023-09-11T08:18:22Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:fluent-bit.conf: {}
          f:parsers.conf: {}
          f:stdout-kubernetes.conf: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2024-09-24T07:11:52Z"
  name: sre-fluent-bit-config
  namespace: logging